version: '3.2'
services:
  Backup-Portainer:
    container_name: Backup
    image: maxens/backup10
    hostname: portainer-backup
    restart: unless-stopped
    command: schedule
    environment:
      BACKUP_ENCRYPTION_KEY: "fxFNy77Vj1pYgG5f"
      TZ: Europe/Paris #set local timezone using TZ database name standard as seen - https://manpages.ubuntu.com/manpages/bionic/man3/DateTime::TimeZone::Catalog.3pm.html
      PORTAINER_BACKUP_URL: "https://portainer.maxens.tech"
      PORTAINER_BACKUP_TOKEN: "ptr_o01zXFQbnwlFSuW59FjTK3DZHZfr1482XBkVJWulRpY="
      PORTAINER_BACKUP_SCHEDULE: "0 0 0 * * *"

    volumes:
      - /docker/npm:/data/npm
      - /docker/vaultwarden:/data/vaultwarden
      - /docker/adguardhome:/data/adguardhome
      - ./config:/config  
  

      
  